apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: testadmin-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: testadmin
    namespace: test
roleRef:
  kind: ClusterRole
  name: testadmin-clusterrole
  apiGroup: rbac.authorization.k8s.io
