version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - dev_network
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - dev_network
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - dev_network
  aspire_dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.3
    environment:
      DASHBOARD__FRONTEND__AUTHMODE: "Unsecured"
      DASHBOARD__RESOURCESERVICECLIENT__URL: "http://resource-server:80"
      DASHBOARD__RESOURCESERVICECLIENT__AUTHMODE: "Unsecured"
    ports:
      - "18888:18888"
      - "4317:18889"
    networks:
      - dev_network
  resource-server:
    image: aspire-resource-server:latest
    environment:
      ResourceProvider: "Docker"
    ports:
      - "8043:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - dev_network
networks:
  dev_network:
    driver: bridge
volumes:
  mysql_data:
  mongo_data:
